name: build-and-publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_ITEMS_PER_PAGE: ${{ secrets.VITE_ITEMS_PER_PAGE }}
      VITE_VND_TO_USD: ${{ secrets.VITE_VND_TO_USD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload Artifact to enable deployment
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Create 404.html for SPA fallback
        run: cp dist/index.html dist/404.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_CD_TOKEN }}
          publish_dir: ./dist